# -*- coding: utf-8 -*-
"""test_pretraining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRaS0u-ddU9ULvV96WZSop4zXNmk0_YL
"""

import unittest
from src.pretraining.dataset import UnannotatedImagesDataset
from src.pretraining.model import create_pretraining_model

class TestPretraining(unittest.TestCase):
    def test_dataset_loading(self):
        dataset = UnannotatedImagesDataset(image_dir='path/to/images')
        self.assertTrue(len(dataset) > 0)

    def test_model_initialization(self):
        model = create_pretraining_model()
        self.assertIsNotNone(model)

if __name__ == '__main__':
    unittest.main()