# -*- coding: utf-8 -*-
"""pretrain_run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRaS0u-ddU9ULvV96WZSop4zXNmk0_YL
"""

from src.pretraining.train import train_pretraining_model

train_pretraining_model(image_dir='path/to/unlabeled/images', epochs=30)