# -*- coding: utf-8 -*-
"""finetune_run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRaS0u-ddU9ULvV96WZSop4zXNmk0_YL
"""

from src.finetuning.train import train_finetune_model

train_finetune_model(
    annotations_files=['/path/to/annotations1.xml', '/path/to/annotations2.xml','/path/to/annotations3.xml'],
    image_dirs=['/path/to/images1', '/path/to/images2','/path/to/images3'],
    augmented_images_dir='/path/to/augmented_frames',
    base_model_checkpoint='/path/to/pretrained/model.pth',
    results_path='/path/to/save/results.pkl',
    checkpoint_dir='/path/to/save/checkpoints'
)