# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRaS0u-ddU9ULvV96WZSop4zXNmk0_YL
"""

from setuptools import setup, find_packages

setup(
    name="frameclassifcation_package",
    version="0.1.0",
    author="Yuvraj Khare",
    author_email="k23051761@kcl.ac.uk",
    description="A package for surgical frame classification using semi-supervised tecniques.",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yuvrajkhare/frame-classification/tree/main/frameclassification_package",
    packages=find_packages(where='src'),
    package_dir={"": "src"},
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.7',
    install_requires=[
        "torch>=1.7",
        "torchvision",
        "timm",
        "numpy",
        "pandas",
        "scikit-learn",
        "matplotlib",
        "seaborn",
        "umap-learn",
        "tqdm",
    ],
    tests_require=[
        "unittest",
        "pytest"
    ],
)
